// Agro Monitor variant - agro.worldmonitor.app
import type { PanelConfig, MapLayers } from '@/types';
import type { VariantConfig } from './base';

export * from './base';
export * from '../agro-geo';
export { SOURCE_TIERS, getSourceTier, SOURCE_TYPES, getSourceType, getSourcePropagandaRisk, type SourceRiskProfile, type SourceType } from '../feeds';
import type { Feed } from '@/types';
import { rssProxyUrl } from '@/utils';
const rss = rssProxyUrl;

export const FEEDS: Record<string, Feed[]> = {
  crops: [
  { name: 'FAO News', url: rss('https://www.fao.org/news/rss-feed/en/') },
  { name: 'WFP News', url: rss('https://www.wfp.org/rss.xml') },
  { name: 'Reuters Agriculture', url: rss('https://news.google.com/rss/search?q=site:reuters.com+(agriculture+OR+wheat+OR+corn+OR+soybeans)+when:2d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Bloomberg Agriculture', url: rss('https://news.google.com/rss/search?q=site:bloomberg.com+(agriculture+OR+crop+prices+OR+food+prices)+when:2d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'AgWeb', url: rss('https://www.agweb.com/rss') },
  { name: 'USDA Reports', url: rss('https://news.google.com/rss/search?q=(USDA+report+OR+USDA+WASDE+OR+NASS)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Agri News', url: rss('https://news.google.com/rss/search?q=(agriculture+OR+farming+OR+harvest+OR+planting)+(news+OR+report)+when:2d&hl=en-US&gl=US&ceid=US:en') },
  ],
  commodityMarkets: [
  { name: 'Wheat & Grains', url: rss('https://news.google.com/rss/search?q=(wheat+price+OR+wheat+futures+OR+CBOT+wheat+OR+grain+price)+when:2d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Corn & Soybeans', url: rss('https://news.google.com/rss/search?q=(corn+price+OR+soybean+price+OR+corn+futures+OR+soy+futures)+when:2d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Coffee & Cocoa', url: rss('https://news.google.com/rss/search?q=(coffee+price+OR+arabica+OR+robusta+OR+cocoa+price)+when:3d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Sugar & Cotton', url: rss('https://news.google.com/rss/search?q=(sugar+price+OR+cotton+price+OR+raw+sugar+OR+sugar+futures)+when:3d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Palm Oil', url: rss('https://news.google.com/rss/search?q=(palm+oil+price+OR+palm+oil+supply+OR+palm+oil+Malaysia)+when:3d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Rice Markets', url: rss('https://news.google.com/rss/search?q=(rice+price+OR+rice+export+OR+rice+ban+OR+rice+futures)+when:3d&hl=en-US&gl=US&ceid=US:en') },
  ],
  foodSecurity: [
  { name: 'Food Crisis', url: rss('https://news.google.com/rss/search?q=(food+crisis+OR+food+insecurity+OR+famine+OR+food+shortage)+when:3d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'FEWS NET', url: rss('https://news.google.com/rss/search?q=(FEWS+NET+OR+food+outlook+OR+IPC+classification)+when:14d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'WFP Operations', url: rss('https://news.google.com/rss/search?q=(World+Food+Programme+OR+WFP)+(hunger+OR+food+OR+nutrition)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Hunger News', url: rss('https://news.google.com/rss/search?q=(hunger+OR+malnutrition+OR+food+aid+OR+humanitarian+food)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  ],
  tradePolicy: [
  { name: 'Export Bans', url: rss('https://news.google.com/rss/search?q=(export+ban+OR+export+restriction)+(wheat+OR+rice+OR+corn+OR+fertilizer+OR+sugar)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Ag Trade Policy', url: rss('https://news.google.com/rss/search?q=(agriculture+tariff+OR+food+trade+OR+grain+deal+OR+food+sanctions)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Fertilizer & Inputs', url: rss('https://news.google.com/rss/search?q=(fertilizer+price+OR+nitrogen+fertilizer+OR+potash+OR+urea)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  ],
  weather: [
  { name: 'Crop Weather', url: rss('https://news.google.com/rss/search?q=(drought+OR+frost+OR+flood+OR+La+Nina+OR+El+Nino)+(crop+OR+harvest+OR+agriculture)+when:3d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Ag Weather Alerts', url: rss('https://news.google.com/rss/search?q=(crop+damage+OR+harvest+loss+OR+drought+warning+OR+heat+wave)+(crop+OR+farm)+when:3d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Monsoon Watch', url: rss('https://news.google.com/rss/search?q=(monsoon+OR+Indian+monsoon)+(agriculture+OR+crop+OR+planting)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  ],
  supplyChain: [
  { name: 'Grain Shipping', url: rss('https://news.google.com/rss/search?q=(grain+shipping+OR+bulk+carrier+OR+grain+terminal+OR+grain+port+OR+grain+corridor)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Locust Watch', url: rss('https://news.google.com/rss/search?q=(desert+locust+OR+locust+swarm+OR+FAO+locust+OR+locust+invasion)+when:14d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Ag Logistics', url: rss('https://news.google.com/rss/search?q=(food+supply+chain+OR+agricultural+supply+OR+crop+logistics)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  ],
  regional: [
  { name: 'Black Sea Grain', url: rss('https://news.google.com/rss/search?q=(Black+Sea+grain+OR+Black+Sea+wheat+OR+Ukraine+wheat+OR+Russia+wheat)+when:3d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Brazil Agri', url: rss('https://news.google.com/rss/search?q=(Brazil+agriculture+OR+Brazil+soy+OR+Brazil+corn+OR+Cerrado)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'India Food & Crop', url: rss('https://news.google.com/rss/search?q=(India+rice+OR+India+wheat+OR+India+food+OR+India+agriculture)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'Africa Food Security', url: rss('https://news.google.com/rss/search?q=(Africa+food+security+OR+Africa+harvest+OR+Sub-Saharan+food)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  { name: 'SE Asia Crops', url: rss('https://news.google.com/rss/search?q=(Southeast+Asia+rice+OR+Vietnam+rice+OR+Thailand+rice+OR+Indonesia+rice)+when:7d&hl=en-US&gl=US&ceid=US:en') },
  ],
};

export const DEFAULT_PANELS: Record<string, PanelConfig> = {
  map:               { name: 'Global Agro Map',        enabled: true, priority: 1 },
  'live-news':       { name: 'Agro Headlines',         enabled: true, priority: 1 },
  insights:          { name: 'AI Agro Insights',       enabled: true, priority: 1 },
  crops:             { name: 'Crop & Harvest News',    enabled: true, priority: 1 },
  commodityMarkets:  { name: 'Commodity Markets',      enabled: true, priority: 1 },
  foodSecurity:      { name: 'Food Security',          enabled: true, priority: 1 },
  tradePolicy:       { name: 'Trade & Export Policy',  enabled: true, priority: 1 },
  weather:           { name: 'Crop Weather',           enabled: true, priority: 1 },
  'satellite-fires': { name: 'Crop Fire Monitor',      enabled: true, priority: 1 },
  supplyChain:       { name: 'Ag Supply Chain',        enabled: true, priority: 1 },
  regional:          { name: 'Regional Markets',       enabled: true, priority: 1 },
  climate:           { name: 'Climate Anomalies',      enabled: true, priority: 2 },
  'macro-signals':   { name: 'Market Radar',           enabled: true, priority: 2 },
  markets:           { name: 'Broader Markets',        enabled: true, priority: 2 },
  polymarket:        { name: 'Predictions',            enabled: true, priority: 2 },
  monitors:          { name: 'My Monitors',            enabled: true, priority: 2 },
};

export const DEFAULT_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: true,
  hotspots: false,
  ais: true,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: true,
  economic: false,
  waterways: true,
  outages: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: true,
  ucdpEvents: false,
  displacement: false,
  climate: true,
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: true,
  iranAttacks: false,
  ciiChoropleth: false,
  dayNight: false,
  cropStress: true,
  agroFires: true,
  locusts: true,
  foodPorts: true,
  agroMarkets: true,
};

export const MOBILE_DEFAULT_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: true,
  economic: false,
  waterways: false,
  outages: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: true,
  ucdpEvents: false,
  displacement: false,
  climate: false,
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  ciiChoropleth: false,
  dayNight: false,
  cropStress: true,
  agroFires: true,
  locusts: false,
  foodPorts: true,
  agroMarkets: false,
};

export const VARIANT_CONFIG: VariantConfig = {
  name: 'agro',
  description: 'Agricultural intelligence, food security, and crop markets dashboard',
  panels: DEFAULT_PANELS,
  mapLayers: DEFAULT_MAP_LAYERS,
  mobileMapLayers: MOBILE_DEFAULT_MAP_LAYERS,
};